CREATE TABLE checkin (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attendee_id VARCHAR(255) NOT NULL,

    CONSTRAINT checkin_attendee_id_fk FOREIGN KEY (attendee_id) REFERENCES attendee (id) ON DELETE RESTRICT ON UPDATE CASCADE
);